debugfs: Add '#include <linux/device.h>' for debugfs.h
"struct device" is used by debugfs.h, but linux/device.h is
not included by it. Without this, kernel building will fail with:

include/linux/debugfs.h:105: error: ‘struct device’ declared inside parameter list

Signed-off-by: Shuangshuang Zhang <zhangshuangshuang@loongson.cn>